# Generated by Django 6.0.1 on 2026-01-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_Cdate",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
