# Generated by Django 6.0.1 on 2026-01-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_post_cdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_url",
            field=models.TextField(default="someurl"),
        ),
    ]
